//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ÜrünStokTakip.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVC_StokTakipEntities : DbContext
    {
        public MVC_StokTakipEntities()
            : base("name=MVC_StokTakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Kategori> Kategori { get; set; }
        public DbSet<Kullanıcı> Kullanıcı { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Sepet> Sepet { get; set; }
        public DbSet<Satislar> Satislar { get; set; }
        public DbSet<Urun> Urun { get; set; }
    }
}
